export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const SET_INGREDIENT_BUN = "SET_INGREDIENT_BUN";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT_DETAILS = "SET_INGREDIENT_DETAILS";
export const SET_ORDER_DETAILS = "SET_ORDER_DETAILS"
